name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/socket/Dockerfile
          push: true
          tags: ammarcodeable/super-tic-tac-toe_socket:latest

      - name: Start container for testing
        run: |
          docker run -d --name socket-test ammarcodeable/super-tic-tac-toe_socket
          sleep 2

      - name: Check container logs
        run: docker logs socket-test

      - name: Check container status
        run: if [ "$(docker inspect -f='{{.State.Status}}' socket-test)" != "running" ]; then exit 1; fi
