name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build socket server Docker image
        run: docker build -f ./apps/socket/Dockerfile -t ammarcodeable/super-tic-tac-toe_socket .

      - name: Start container
        run: |
          docker run -d --name socket-test ammarcodeable/super-tic-tac-toe_socket
          sleep 2

      - name: Check container logs
        run: docker logs socket-test

      - name: Check container status
        run: if [ "$(docker inspect -f='{{.State.Status}}' socket-test)" != "running" ]; then exit 1; fi
